--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Arisify/yamlcomments
build-by-default: true
branches:
- master
projects:
  yamlcomments:
    path: ""
    model: virion
    type: library
...
